name: roshub-ble-serial-server
version: '0.1'
summary: ble device service
description: ble device service
icon: icons/roshub_vector_logo-256x256.png
base: core18
confinement: strict
grade: stable

architectures:
  - build-on: amd64
    run-on: amd64

  - build-on: i386
    run-on: i386

  - build-on: armhf
    run-on: armhf

  - build-on: arm64
    run-on: arm64

apps:
  ble-serial-server:
    command: bin/bleSerialServer

parts:
  qt:
    source: "./src"
    plugin: qmake
    project-files:
      - bleSerialServer.pro
    build-packages:
      - build-essential
      - libssl-dev
      - qtbase5-dev
      - qtconnectivity5-dev
    stage-packages:
      # Here for the plugins-- they're not linked in automatically.
      - libqt5bluetooth5

